# Generated by Django 5.1.3 on 2025-12-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra_clave', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_scraping', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_scraping'],
            },
        ),
    ]
